output: /dir
since: "18.09.2023"
until: "18.10.2023"
artifacts:
- ghUsername: pPrecel
  ghPersonalAccessToken: <TOKEN>
  repos:
  - kyma-project/kyma
  - kyma-project/serverless-manager
  - kyma-project/keda-manager
  - kyma-project/test-infra
  - kyma-incubator/reconciler
- ghUsername: my-enterprise-username
  ghPersonalAccessToken: <ENTERPRISE-TOKEN>
  ghEnterpriseURL: https://your.org.enterprise.com/
  repos:
  - ...
report:
  template: /path/to/template.docx
  fields:
  - pkupGenEmployeesName: John Wick
  - pkupGenJobTitle: Assasin
  - ...