on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: build
jobs:

  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - 
      uses: actions/checkout@v3
    - 
      uses: actions/setup-go@v3g
    - 
      name: Verify
      run: make verify
    - 
      name: Build
      run: make build
